#
# Copyright (c) 2006-2020 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        sw_port_scanner:
            enable: true
            category: "Network"
            name: "SW Port Scanner"
            description: " Uses web workers to port scan"
            authors: ["Crimes by Will", "jcrew99"]
            # http://caniuse.com/cors
            target:
                working: ["ALL"]
                not_working:
                    # CORS is partially supported on IE 8 & 9
                    IE:
                        min_ver: 6
                        max_ver: 7
                    O:
                        min_ver: 1
                        max_ver: 11
                    C:
                        min_ver: 1
                        max_ver: 3
                    S:
                        min_ver: 1
                        max_ver: 3
                    F:
                        min_ver: 1
                        max_ver: 3
